# External gems
gems:
  - jekyll-sitemap

# Site settings
header: "TALENT"
title: "Teaching Talent"
subtitle: "Building the Best"
email: hello@teachingtalent.org
name: "Teaching Talent"
description: > 
  We are a network of teaching schools on a collaborative journey to help develop the best possible teachers and leaders for Buckinghamshire schools.
baseurl: "/" # the subpath of your site, e.g. /blog/
url: "http://teachingtalent.org" # the base hostname & protocol for your site
cover: "assets/header_6_fl.jpg"
logo: "assets/logo.png"

# Build settings
markdown: kramdown
paginate: 5
paginate_path: "/page:num/"

# Disqus comments
disqus_shortname: 

# Google analytics
ga_tracking_id: "UA-67613530-1"

# Category descriptions (for archive pages)
descriptions:
  - cat: case-studies
    desc: "What we do, how we do it and who benefits."

  - cat: events
    desc: "What's coming up at Talent."

# Custom vars
version:          		1.0.0
post_assets:			assets/posts
general_assets:			assets/general

# Social icons and sharing options
#
# Social settings are used in two places:
# * In the footer, as links to your personal profiles
# * After each blog post for sharing widgets
# 
# Example:
# 
# social:
#   - name: Twitter                         # Name of the service
#     icon: twitter                         # Font Awesome icon to use (minus fa- prefix)
#     username: "@TheBenCentra"             # (User) Name to display in the footer link
#     url: https://twitter.com/TheBenCentra # URL of your profile (leave blank to not display in footer)
#     desc: Follow me on Twitter            # Description to display as link title, etc
#     share_url: http://twitter.com/share   # URL for sharing to the service (leave blank to not allow sharing)
#     share_title: ?text=                   # Title parameter for sharing URL
#     share_link: "&amp;url="               # Link parameter for sharing URL
social:
  - name: Twitter
    icon: twitter
    username: "@talent_teaching"
    url: https://twitter.com/talent_teaching
    desc: Follow us on Twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

  - name: Facebook
    icon: facebook
    username: talent_teaching
    url: 
    desc: Like us on Facebook
    share_url: //www.facebook.com/sharer.php
    share_title: ?t=
    share_link: "&amp;u="

  - name: GitHub
    icon: github
    username: Teaching-Talent
    url: https://github.com/Teaching-Talent
    desc: Work with us on GitHub
    share_url:
    share_title:
    share_link:

  - name: LinkedIn
    icon: linkedin
    username: 
    url: 
    desc: Connect with us on LinkedIn
    share_url: //www.linkedin.com/shareArticle
    share_title: ?mini=true
    share_link: "&amp;url="

  - name: Google+
    icon: google-plus
    username: 
    url: 
    desc: Add me to your Circles
    share_url: //plus.google.com/share
    share_title: ?title=
    share_link: "&amp;url="

  - name: YouTube
    icon: youtube
    username: 
    url: 
    desc: Subscribe on YouTube
    share_url: 
    share_title: 
    share_link:

  - name: Instagram
    icon: instagram
    username: 
    url: 
    desc: Follow me on Instagram
    share_url: 
    share_title: 
    share_link:

  - name: Pinterest
    icon: pinterest
    username: 
    url: 
    desc: Follow me on Pinterest
    share_url: 
    share_title: 
    share_link:

  - name: SoundCloud
    icon: soundcloud
    username: 
    url: 
    desc: Follow me on SoundCloud
    share_url: 
    share_title: 
    share_link:

  - name: Tumblr
    icon: tumblr
    username: 
    url: 
    desc: Follow me on Tumblr
    share_url: 
    share_title: 
    share_link:

  - name: Steam
    icon: steam
    username: 
    url: 
    desc: Friend me on Steam
    share_url: 
    share_title: 
    share_link:

  - name: Dribbble
    icon: dribbble
    username: 
    url: 
    desc: Follow me on Dribble

  - name: Vimeo
    icon: vimeo-square
    username: 
    url: 
    desc: Follow me on Vimeo

  - name: Vine
    icon: vine
    username: 
    url: 
    desc: Follow me on Vine

partners:
  - name: Astra Learning Alliance
    school: Dr Challoner’s Grammar School
    url: http://astra-alliance.com

  - name: Cygnus
    school: Wycombe High School
    url: http://www.cygnustsa.co.uk

  - name: Marlow & Maidenhead Learning Alliance
    school: Sir William Borlase’s Grammar School
    url: http://www.swbgs.com

# Social sharing protocols
# These are for automatically generating sharing metadata for FB and Twitter
# OS Protocol is for sharing the source of your site, if you're interested. For more, see osprotocol.com
protocols:
    fb_image: "assets/logo.png"
    fb_image_width: 612
    fb_image_height: 605
    fb_image_type: "image/png"

    twitter_image: "assets/logo.png"

    os_repo: "https://github.com/RichardLitt/wordhoardpress.com"
    os_rcs_type: "git"
    os_src: "git@github.com:RichardLitt/wordhoardpress.com.git"
